export const SET_APP_THEME = 'SET_APP_THEME';


export const FETCH_NOTE = 'FETCH_NOTE';
export const FETCH_NOTE_SUCCESS = 'FETCH_NOTE_SUCCESS';
export const FETCH_NOTE_FAILURE = 'FETCH_NOTE_FAILURE';

export const REFETCH_NOTE = 'REFETCH_NOTE';
export const REFETCH_NOTE_SUCCESS = 'REFETCH_NOTE_SUCCESS';
export const REFETCH_NOTE_FAILURE = 'REFETCH_NOTE_FAILURE';

export const FETCH_PAGINATED_NOTES = 'FETCH_PAGINATED_NOTES';
export const FETCH_PAGINATED_NOTES_SUCCESS = 'FETCH_PAGINATED_NOTES_SUCCESS';
export const FETCH_PAGINATED_NOTES_FAILURE = 'FETCH_PAGINATED_NOTES_FAILURE';

export const FETCH_TRASHED_NOTES = 'FETCH_TRASHED_NOTES';
export const FETCH_TRASHED_NOTES_SUCCESS = 'FETCH_TRASHED_NOTES_SUCCESS';
export const FETCH_TRASHED_NOTES_FAILURE = 'FETCH_TRASHED_NOTES_FAILURE';

export const EMPTY_TRASH = 'EMPTY_TRASH';

export const DELETE_NOTE = 'DELETE_NOTE';
export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS';
export const DELETE_NOTE_FAILURE = 'DELETE_NOTE_FAILURE';

export const DELETE_TRASHED_NOTE = 'DELETE_TRASHED_NOTE';
export const DELETE_TRASHED_NOTE_SUCCESS = 'DELETE_NOTE_TRASHED_SUCCESS';
export const DELETE_TRASHED_NOTE_FAILURE = 'DELETE_NOTE_TRASHED_FAILURE';

export const RESTORE_TRASHED_NOTE = 'RESTORE_TRASHED_NOTE';
export const RESTORE_TRASHED_NOTE_SUCCESS = 'RESTORE_NOTE_TRASHED_SUCCESS';
export const RESTORE_TRASHED_NOTE_FAILURE = 'RESTORE_NOTE_TRASHED_FAILURE';

export const ACTIONS = {
	SET_APP_THEME,
	FETCH_NOTE,
	FETCH_NOTE_SUCCESS,
	FETCH_NOTE_FAILURE,
	FETCH_PAGINATED_NOTES,
	FETCH_PAGINATED_NOTES_SUCCESS,
	FETCH_PAGINATED_NOTES_FAILURE,
	DELETE_NOTE,
	DELETE_NOTE_SUCCESS,
	DELETE_NOTE_FAILURE,
};