export const SET_APP_THEME = 'SET_APP_THEME';


export const FETCH_NOTE = 'DELETE_NOTE';
export const FETCH_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS';
export const FETCH_NOTE_FAILURE = 'DELETE_NOTE_FAILURE';

export const FETCH_PAGINATED_NOTES = 'FETCH_PAGINATED_NOTES';
export const FETCH_PAGINATED_NOTES_SUCCESS = 'FETCH_PAGINATED_NOTES_SUCCESS';
export const FETCH_PAGINATED_NOTES_FAILURE = 'FETCH_PAGINATED_NOTES_FAILURE';


export const DELETE_NOTE = 'DELETE_NOTE';
export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS';
export const DELETE_NOTE_FAILURE = 'DELETE_NOTE_FAILURE';


export const ACTIONS = {
	SET_APP_THEME,
	FETCH_NOTE,
	FETCH_NOTE_SUCCESS,
	FETCH_NOTE_FAILURE,
	FETCH_PAGINATED_NOTES,
	FETCH_PAGINATED_NOTES_SUCCESS,
	FETCH_PAGINATED_NOTES_FAILURE,
	DELETE_NOTE,
	DELETE_NOTE_SUCCESS,
	DELETE_NOTE_FAILURE,
};