"""empty message

Revision ID: 68008dcf6ce4
Revises: 667b4e15bfcd
Create Date: 2020-09-17 19:07:16.852797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68008dcf6ce4'
down_revision = '667b4e15bfcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
